#!/usr/bin/env php
<?php

namespace progpilot;

if(file_exists(__DIR__.'/vendor/autoload.php'))
    require_once __DIR__.'/vendor/autoload.php';

else if(file_exists(__DIR__.'/../../../../autoload.php'))
    require_once __DIR__.'/../../../../autoload.php';
    
else
    die('You must set up the project dependencies');

use progpilot\Command\ProgpilotCommand;
use progpilot\Console\Application;

$application = new Application();
$application->add(new ProgpilotCommand);
$status = $application->run();
exit($status);

?>	 
