<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'cb36d7468e442c354c5037bbb4d59b1c' => $vendorDir . '/progpilot/tests/test_package/init.php',
);
